mode: single
blueprint:
  name: Advanced Presence Control with MQTT Button
  author: wkethman
  description: >-
    Automates home/away modes based on a binary_sensor. Includes a guest mode 
    that activates an MQTT button (single press for home, hold for away). 
    An input_boolean reflects the current state (on=Home, off=Away).
  domain: automation
  input:
    presence_sensor:
      name: Presence Sensor
      description: The binary_sensor to track presence (on = Home, off = Away).
      selector:
        entity:
          domain: binary_sensor
    home_mode_boolean:
      name: Home Mode Boolean
      description: The input_boolean that will represent the home's state (on = Home, off = Away).
      selector:
        entity:
          domain: input_boolean
    guest_mode_toggle:
      name: Guest Mode Toggle
      description: An input_boolean that enables (on) or disables (off) Guest Mode.
      selector:
        entity:
          domain: input_boolean
    mqtt_topic:
      name: MQTT Topic
      description: The MQTT topic your button publishes its state to.
      default: "zigbee2mqtt/<device_name>/action"
      selector:
        text:
    payload_click:
      name: Payload for Single Press
      description: The MQTT payload that signifies a single press/click.
      default: "single"
      selector:
        text:
    payload_hold:
      name: Payload for Hold
      description: The MQTT payload that signifies a hold action.
      default: "hold"
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: mqtt
    topic: !input mqtt_topic
    payload: !input payload_click
    id: "mqtt_click"
  - platform: mqtt
    topic: !input mqtt_topic
    payload: !input payload_hold
    id: "mqtt_hold"

condition: []

action:
  - choose:
      # OPTION 1: Set AWAY mode (manual or automatic).
      - conditions:
          - condition: or
            conditions:
              # Condition A: Manual away via HOLD, ONLY if guest mode is ON.
              - condition: and
                conditions:
                  - condition: trigger
                    id: "mqtt_hold"
                  - condition: template
                    value_template: "{{ is_state(!input guest_mode_toggle, 'on') }}"

              # Condition B: Automatic away when sensor is OFF and guest mode is OFF.
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ is_state(!input presence_sensor, 'off') }}"
                  - condition: template
                    value_template: "{{ is_state(!input guest_mode_toggle, 'off') }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input home_mode_boolean

      # OPTION 2: Set HOME mode.
      # Happens if presence sensor is ON OR if a manual CLICK happens while guest mode is ON.
      - conditions:
          - condition: template
            value_template: "{{ is_state(!input presence_sensor, 'on') or (trigger.id == 'mqtt_click' and is_state(!input guest_mode_toggle, 'on')) }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input home_mode_boolean
